<?php
require_once __DIR__.'/config/database.php';require_once __DIR__.'/config/csrf.php';requireLogin('cart.php');$uid=currentUserId();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verifyCsrf($_POST['csrf_token']??null))$error='Invalid security token. Please refresh and try again.';else{
  $action=$_POST['action']??'';$id=(int)($_POST['cart_item_id']??0);
  if($action==='remove'){$s=$pdo->prepare('DELETE FROM cart_items WHERE cart_item_id=? AND user_id=?');$s->execute([$id,$uid]);}
  elseif($action==='update'){$q=filter_var($_POST['quantity']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($q===false)$error='Quantity must be at least 1.';else{$s=$pdo->prepare('SELECT c.cart_item_id,p.stock FROM cart_items c JOIN products p ON p.product_id=c.product_id WHERE c.cart_item_id=? AND c.user_id=?');$s->execute([$id,$uid]);$row=$s->fetch();if(!$row)$error='Cart item not found.';elseif($q>$row['stock'])$error='Only '.(int)$row['stock'].' item(s) are available.';else{$u=$pdo->prepare('UPDATE cart_items SET quantity=? WHERE cart_item_id=? AND user_id=?');$u->execute([$q,$id,$uid]);}}}
 }
}
$s=$pdo->prepare('SELECT c.cart_item_id,c.quantity,p.product_id,p.product_name,p.price,p.image,p.stock FROM cart_items c JOIN products p ON p.product_id=c.product_id WHERE c.user_id=? ORDER BY c.created_at DESC');$s->execute([$uid]);$items=$s->fetchAll();$total=0;foreach($items as $i)$total+=(float)$i['price']*(int)$i['quantity'];
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>My Cart | Dionisio Fitness Center</title><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/style.css"></head><body class="auth-page"><div class="auth-shell wide-shell"><a href="index.php" class="auth-brand"><span class="brand-mark">D</span><span class="brand-text"><strong>DIONISIO</strong><small>FITNESS CENTER</small></span></a><div class="account-card"><div class="auth-copy"><p class="eyebrow">SHOPPING</p><h1>MY <span>CART.</span></h1><p>Review your Dionisio merch before checkout.</p></div><?php if($error):?><div class="auth-alert"><?=e($error)?></div><?php endif;?><?php if(!$items):?><div class="empty-state"><h3>YOUR CART IS EMPTY</h3><p>Add a product from the merch page to get started.</p><a class="btn btn-red" href="merch.php">SHOP MERCH</a></div><?php else:?><div class="cart-list"><?php foreach($items as $i):?><div class="cart-row"><div class="cart-product"><div class="cart-thumb"><?php if($i['image']):?><img src="assets/<?=e($i['image'])?>" alt="<?=e($i['product_name'])?>"><?php endif;?></div><div><h3><?=e($i['product_name'])?></h3><p>₱<?=number_format((float)$i['price'],2)?> • Stock left: <?=number_format((int)$i['stock'])?></p></div></div><form method="POST" class="cart-qty"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><input type="hidden" name="action" value="update"><input type="hidden" name="cart_item_id" value="<?=$i['cart_item_id']?>"><input type="number" name="quantity" min="1" max="<?=$i['stock']?>" value="<?=$i['quantity']?>"><button type="submit">UPDATE</button></form><strong>₱<?=number_format((float)$i['price']*(int)$i['quantity'],2)?></strong><form method="POST"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><input type="hidden" name="action" value="remove"><input type="hidden" name="cart_item_id" value="<?=$i['cart_item_id']?>"><button class="remove-btn" type="submit">REMOVE</button></form></div><?php endforeach;?></div><div class="cart-total"><span>TOTAL</span><strong>₱<?=number_format($total,2)?></strong></div><div class="account-actions"><a href="merch.php">CONTINUE SHOPPING</a><a class="btn btn-red" href="checkout.php">PROCEED TO CHECKOUT</a></div><?php endif;?><a class="auth-back" href="account.php">← BACK TO MY ACCOUNT</a></div></div></body></html>
