<?php
require_once __DIR__.'/config/database.php';require_once __DIR__.'/config/csrf.php';requireLogin('checkout.php');$uid=currentUserId();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verifyCsrf($_POST['csrf_token']??null))$error='Invalid security token. Please refresh and try again.';else{
  try{$pdo->beginTransaction();
   $q=$pdo->prepare('SELECT c.product_id,c.quantity,p.product_name,p.price,p.stock,p.image FROM cart_items c JOIN products p ON p.product_id=c.product_id WHERE c.user_id=? FOR UPDATE');$q->execute([$uid]);$items=$q->fetchAll();if(!$items)throw new Exception('Your cart is empty.');
   $total=0;foreach($items as $i){if((int)$i['quantity']>(int)$i['stock'])throw new Exception('Sorry, only '.(int)$i['stock'].' item(s) of '.$i['product_name'].' are available.');$total+=(float)$i['price']*(int)$i['quantity'];}
   $ins=$pdo->prepare("INSERT INTO orders(user_id,total_amount,status) VALUES(?,?, 'Pending')");$ins->execute([$uid,$total]);$orderId=(int)$pdo->lastInsertId();
   $oi=$pdo->prepare('INSERT INTO order_items(order_id,product_id,product_name,price,quantity,subtotal) VALUES(?,?,?,?,?,?)');$dec=$pdo->prepare('UPDATE products SET stock=stock-? WHERE product_id=? AND stock>=?');
   foreach($items as $i){$sub=(float)$i['price']*(int)$i['quantity'];$oi->execute([$orderId,$i['product_id'],$i['product_name'],$i['price'],$i['quantity'],$sub]);$dec->execute([$i['quantity'],$i['product_id'],$i['quantity']]);if($dec->rowCount()!==1)throw new Exception('Stock changed while checking out. Please try again.');}
   $clear=$pdo->prepare('DELETE FROM cart_items WHERE user_id=?');$clear->execute([$uid]);$pdo->commit();header('Location: order_details.php?id='.$orderId.'&placed=1');exit;
  }catch(Throwable $ex){if($pdo->inTransaction())$pdo->rollBack();$error=$ex->getMessage();}
 }
}
$q=$pdo->prepare('SELECT c.quantity,p.product_name,p.price,p.stock FROM cart_items c JOIN products p ON p.product_id=c.product_id WHERE c.user_id=?');$q->execute([$uid]);$items=$q->fetchAll();$total=0;foreach($items as $i)$total+=(float)$i['price']*(int)$i['quantity'];
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Checkout | Dionisio Fitness Center</title><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/style.css"></head><body class="auth-page"><div class="auth-shell wide-shell"><a href="index.php" class="auth-brand"><span class="brand-mark">D</span><span class="brand-text"><strong>DIONISIO</strong><small>FITNESS CENTER</small></span></a><div class="account-card"><div class="auth-copy"><p class="eyebrow">CHECKOUT</p><h1>COMPLETE <span>ORDER.</span></h1><p>Confirm your order. Payment is not processed online in this school-project version.</p></div><?php if($error):?><div class="auth-alert"><?=e($error)?></div><?php endif;?><?php if(!$items):?><div class="empty-state"><h3>YOUR CART IS EMPTY</h3><a class="btn btn-red" href="merch.php">SHOP MERCH</a></div><?php else:?><div class="checkout-list"><?php foreach($items as $i):?><div><span><?=e($i['product_name'])?> × <?=number_format((int)$i['quantity'])?></span><strong>₱<?=number_format((float)$i['price']*(int)$i['quantity'],2)?></strong></div><?php endforeach;?></div><div class="cart-total"><span>TOTAL</span><strong>₱<?=number_format($total,2)?></strong></div><form method="POST" class="auth-form"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><p class="checkout-note">Your order will be recorded as <strong>PENDING</strong>. Stock is deducted only after the order is successfully recorded.</p><button class="btn btn-red auth-submit" type="submit">PLACE ORDER</button></form><?php endif;?><a class="auth-back" href="cart.php">← BACK TO CART</a></div></div></body></html>
