<?php
require_once __DIR__.'/config/database.php'; require_once __DIR__.'/config/csrf.php'; requireLogin('join.php');
$userId=currentUserId(); $stmt=$pdo->prepare('SELECT full_name,email FROM users WHERE id=?'); $stmt->execute([$userId]); $user=$stmt->fetch(); if(!$user){session_destroy();header('Location: login.php');exit;}
$plans=['Basic'=>999,'Premium'=>1499,'VIP'=>2499]; $selected=$_POST['plan']??'Premium'; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verifyCsrf($_POST['csrf_token']??null)) $error='Your session expired. Please try again.';
 elseif(!isset($plans[$selected])) $error='Please select a valid membership plan.';
 else{
  try{$pdo->beginTransaction();
   $old=$pdo->prepare("UPDATE memberships SET status='Expired' WHERE user_id=? AND status='Active'"); $old->execute([$userId]);
   $price=$plans[$selected]; $ins=$pdo->prepare("INSERT INTO memberships (user_id,plan,price,status,start_date,expiration_date) VALUES (?,?,?,'Active',CURDATE(),DATE_ADD(CURDATE(),INTERVAL 1 MONTH))"); $ins->execute([$userId,$selected,$price]);
   $pdo->commit(); header('Location: account.php?membership=success');exit;
  }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='We could not save your membership. Please try again.';}
 }
}
function planText($plan){return ['Basic'=>'Gym access • Locker room • Open gym','Premium'=>'All equipment • Personal training • Nutrition guidance','VIP'=>'Premium benefits • Custom meal plan • VIP lounge'][$plan];}
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Join Dionisio | Dionisio Fitness Center</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/style.css"></head><body class="auth-page"><div class="auth-shell"><a href="index.php" class="auth-brand"><span class="brand-mark">D</span><span class="brand-text"><strong>DIONISIO</strong><small>FITNESS CENTER</small></span></a><div class="join-card"><div class="auth-copy"><p class="eyebrow">MEMBERSHIP</p><h1>CHOOSE YOUR <span>PLAN.</span></h1><p>Welcome, <?=e($user['full_name'])?>. Choose your membership to activate it on your account.</p></div><?php if($error):?><div class="auth-alert"><?=e($error)?></div><?php endif;?><form method="POST"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><div class="membership-options"><?php foreach($plans as $plan=>$price):?><label class="membership-option <?=$selected===$plan?'selected':''?> <?=$plan==='Premium'?'featured-option':''?>"><input type="radio" name="plan" value="<?=e($plan)?>" <?=$selected===$plan?'checked':''?>><span><strong><?=e(strtoupper($plan))?> <?=$plan==='Premium'?'<i>MOST POPULAR</i>':''?></strong><b>₱<?=number_format($price)?> <small>/ MONTH</small></b><em><?=e(planText($plan))?></em></span></label><?php endforeach;?></div><button class="btn btn-red auth-submit" type="submit">ACTIVATE <?=e(strtoupper($selected))?> MEMBERSHIP</button></form><div class="account-mini"><span>Signed in as <strong><?=e($user['email'])?></strong></span><a href="account.php">MY ACCOUNT</a><a href="logout.php">SIGN OUT</a></div></div></div><script>document.querySelectorAll('input[name="plan"]').forEach(r=>r.addEventListener('change',()=>{document.querySelectorAll('.membership-option').forEach(x=>x.classList.remove('selected'));r.closest('.membership-option').classList.add('selected');}));</script></body></html>
