<?php
require_once __DIR__.'/config/database.php';require_once __DIR__.'/config/csrf.php';requireLogin('profile.php');$uid=currentUserId();$errors=[];$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verifyCsrf($_POST['csrf_token']??null))$errors[]='Your session expired. Please try again.';else{
  $name=trim($_POST['full_name']??'');$email=strtolower(trim($_POST['email']??''));$phone=trim($_POST['phone']??'');
  if($name===''||mb_strlen($name)>120)$errors[]='Please enter your full name.';if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Please enter a valid email address.';
  if(!$errors){$s=$pdo->prepare('SELECT id FROM users WHERE email=? AND id<>? LIMIT 1');$s->execute([$email,$uid]);if($s->fetch())$errors[]='That email is already being used.';}
  if(!$errors){$s=$pdo->prepare('UPDATE users SET full_name=?,email=?,phone=? WHERE id=?');$s->execute([$name,$email,$phone?:null,$uid]);$_SESSION['user_name']=$name;$_SESSION['user_email']=$email;$success='Profile updated successfully.';}
 }
}
$s=$pdo->prepare('SELECT full_name,email,phone,created_at FROM users WHERE id=?');$s->execute([$uid]);$user=$s->fetch();
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>My Profile | Dionisio Fitness Center</title><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/style.css"></head><body class="auth-page"><div class="auth-shell"><a href="index.php" class="auth-brand"><span class="brand-mark">D</span><span class="brand-text"><strong>DIONISIO</strong><small>FITNESS CENTER</small></span></a><div class="auth-card"><div class="auth-copy"><p class="eyebrow">ACCOUNT</p><h1>MY <span>PROFILE.</span></h1><p>Update your personal account information.</p></div><?php if($errors):?><div class="auth-alert"><?=e(implode(' ',$errors))?></div><?php endif;?><?php if($success):?><div class="auth-success"><?=e($success)?></div><?php endif;?><form method="POST" class="auth-form"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><div class="form-group"><label>FULL NAME</label><input name="full_name" value="<?=e($user['full_name'])?>" required maxlength="120"></div><div class="form-group"><label>EMAIL ADDRESS</label><input type="email" name="email" value="<?=e($user['email'])?>" required></div><div class="form-group"><label>PHONE NUMBER</label><input name="phone" value="<?=e($user['phone'])?>" maxlength="30"></div><div class="profile-date">ACCOUNT CREATED: <strong><?=e($user['created_at'])?></strong></div><button class="btn btn-red auth-submit" type="submit">SAVE CHANGES</button></form><a class="auth-back" href="account.php">← BACK TO MY ACCOUNT</a></div></div></body></html>
